package droolRule ;
import com.example.demo.drools.entity.QueryParam ;
import com.example.demo.drools.entity.RuleResult;
import com.example.demo.drools.service.impl.RuleEngineServiceImpl
import org.slf4j.Logger
import org.slf4j.LoggerFactory
import java.util.ArrayList
import java.util.List ;

dialect  "java"
rule "paramcheck1"
    salience 99
    when queryParam : QueryParam(max > 0)
        resultParam : RuleResult()
    then
        final Logger LOGGER = LoggerFactory.getLogger("param-check-one 规则引擎") ;
        LOGGER.info("参数:getParamId="+queryParam.getParamId()+";getParamSign="+queryParam.getParamSign());
        RuleEngineServiceImpl ruleEngineService = new RuleEngineServiceImpl() ;
        ruleEngineService.executeAddRule(queryParam);
        resultParam.setPostCodeResult(true);
end


//dialect  "java"
rule "paramcheck2"
    salience 88
    when queryParam : QueryParam(paramId != null && paramSign.equals("-"))
        resultParam : RuleResult()
    then
        final Logger LOGGER = LoggerFactory.getLogger("param-check-one 规则引擎") ;
        LOGGER.info("参数:getParamId="+queryParam.getParamId()+";getParamSign="+queryParam.getParamSign());
        RuleEngineServiceImpl ruleEngineService = new RuleEngineServiceImpl() ;
        ruleEngineService.executeRemoveRule(queryParam);
        resultParam.setPostCodeResult(true);
end
//global java.util.List myGlobalList;
//rule "Using a global"
//when
//    eval(true)
//then
//    myGlobalList.add( "Hello World" );
//    final Logger LOGGER = LoggerFactory.getLogger("param-check-one 规则引擎") ;
//         LOGGER.info("参数:getParamId="+queryParam.getParamId()+";getParamSign="+queryParam.getParamSign());
//end